  version: '3.8'
  services:
    db:
      image: mysql:8.0
      container_name: jumoney-db
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        TZ: Asia/Seoul
      ports:
        - "3306:3306"
      volumes:
        - mysql-data:/var/lib/mysql

    redis:
      image: redis:latest
      container_name: jumoney-redis
      command: redis-server --requirepass ${REDIS_PASSWORD}
      ports:
        - "6379:6379"

  volumes:
    mysql-data: