CREATE TABLE user_rankings (
    user_ranking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    master_id BIGINT,
    total_asset NUMERIC(20, 4) NOT NULL,
    total_profit_rate NUMERIC(10, 4) NOT NULL,
    overall_rank INTEGER NOT NULL,
    master_rank INTEGER,
    ranking_date DATE NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_user_ranking_user UNIQUE (user_id),
    CONSTRAINT fk_user_ranking_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_user_ranking_master FOREIGN KEY (master_id) REFERENCES masters(master_id) ON DELETE SET NULL
);

CREATE INDEX idx_user_ranking_overall_rank ON user_rankings(overall_rank);
CREATE INDEX idx_user_ranking_master_rank ON user_rankings(master_id, master_rank);
