CREATE TABLE master_choice_backtest_financials (
    backtest_financial_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id BIGINT NOT NULL,
    settlement_year_month VARCHAR(6) NOT NULL,
    available_date DATE NOT NULL,
    roe NUMERIC(19, 4),
    current_eps NUMERIC(19, 4),
    last_year_eps NUMERIC(19, 4),
    debt_ratio NUMERIC(19, 4),
    current_sales BIGINT,
    last_year_sales BIGINT,
    operating_profit BIGINT,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_master_choice_backtest_financial_stock_settlement UNIQUE (stock_id, settlement_year_month),
    CONSTRAINT fk_master_choice_backtest_financial_stock FOREIGN KEY (stock_id) REFERENCES stocks(stock_id)
);

CREATE INDEX idx_master_choice_backtest_financial_stock_available
    ON master_choice_backtest_financials(stock_id, available_date);

CREATE TABLE master_choice_backtest_daily_indicators (
    daily_indicator_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id BIGINT NOT NULL,
    trade_date DATE NOT NULL,
    margin_debt_rate NUMERIC(19, 4),
    institution_net_buy_quantity BIGINT,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_master_choice_backtest_daily_indicator_stock_trade_date UNIQUE (stock_id, trade_date),
    CONSTRAINT fk_master_choice_backtest_daily_indicator_stock FOREIGN KEY (stock_id) REFERENCES stocks(stock_id)
);

CREATE INDEX idx_master_choice_backtest_daily_indicator_stock_trade_date
    ON master_choice_backtest_daily_indicators(stock_id, trade_date);
