--
-- PostgreSQL database dump
--


-- Dumped from database version 15.17 (Debian 15.17-1.pgdg13+1)
-- Dumped by pg_dump version 15.17 (Debian 15.17-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: hojumoney_personas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.hojumoney_personas (
    hojumoney_persona_id bigint NOT NULL,
    investment_horizon character varying(40) NOT NULL,
    investment_purpose character varying(40) NOT NULL,
    risk_profile character varying(40) NOT NULL,
    persona_name character varying(100) NOT NULL,
    persona_description text NOT NULL,
    CONSTRAINT hojumoney_personas_investment_horizon_check CHECK (((investment_horizon)::text = ANY ((ARRAY['CAPITAL_PROTECTION'::character varying, 'DIVIDEND_INCOME'::character varying, 'STEADY_GROWTH'::character varying, 'CAPITAL_GAIN'::character varying, 'STABILITY'::character varying, 'SAFE_PURSUIT'::character varying, 'PROFIT_PURSUIT'::character varying, 'AGGRESSIVE'::character varying, 'ULTRA_SHORT'::character varying, 'SHORT'::character varying, 'MID'::character varying, 'LONG'::character varying])::text[]))),
    CONSTRAINT hojumoney_personas_investment_purpose_check CHECK (((investment_purpose)::text = ANY ((ARRAY['CAPITAL_PROTECTION'::character varying, 'DIVIDEND_INCOME'::character varying, 'STEADY_GROWTH'::character varying, 'CAPITAL_GAIN'::character varying, 'STABILITY'::character varying, 'SAFE_PURSUIT'::character varying, 'PROFIT_PURSUIT'::character varying, 'AGGRESSIVE'::character varying, 'ULTRA_SHORT'::character varying, 'SHORT'::character varying, 'MID'::character varying, 'LONG'::character varying])::text[]))),
    CONSTRAINT hojumoney_personas_risk_profile_check CHECK (((risk_profile)::text = ANY ((ARRAY['CAPITAL_PROTECTION'::character varying, 'DIVIDEND_INCOME'::character varying, 'STEADY_GROWTH'::character varying, 'CAPITAL_GAIN'::character varying, 'STABILITY'::character varying, 'SAFE_PURSUIT'::character varying, 'PROFIT_PURSUIT'::character varying, 'AGGRESSIVE'::character varying, 'ULTRA_SHORT'::character varying, 'SHORT'::character varying, 'MID'::character varying, 'LONG'::character varying])::text[])))
);


--
-- Name: hojumoney_personas_hojumoney_persona_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.hojumoney_personas ALTER COLUMN hojumoney_persona_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hojumoney_personas_hojumoney_persona_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hojumoney_recommendations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.hojumoney_recommendations (
    hojumoney_recommendation_id bigint NOT NULL,
    recommendation_id bigint NOT NULL,
    investment_horizon character varying(40) NOT NULL,
    investment_purpose character varying(40) NOT NULL,
    risk_profile character varying(40) NOT NULL,
    persona_name character varying(100) NOT NULL,
    persona_description text NOT NULL,
    selected_option_ids jsonb NOT NULL,
    CONSTRAINT hojumoney_recommendations_investment_horizon_check CHECK (((investment_horizon)::text = ANY ((ARRAY['CAPITAL_PROTECTION'::character varying, 'DIVIDEND_INCOME'::character varying, 'STEADY_GROWTH'::character varying, 'CAPITAL_GAIN'::character varying, 'STABILITY'::character varying, 'SAFE_PURSUIT'::character varying, 'PROFIT_PURSUIT'::character varying, 'AGGRESSIVE'::character varying, 'ULTRA_SHORT'::character varying, 'SHORT'::character varying, 'MID'::character varying, 'LONG'::character varying])::text[]))),
    CONSTRAINT hojumoney_recommendations_investment_purpose_check CHECK (((investment_purpose)::text = ANY ((ARRAY['CAPITAL_PROTECTION'::character varying, 'DIVIDEND_INCOME'::character varying, 'STEADY_GROWTH'::character varying, 'CAPITAL_GAIN'::character varying, 'STABILITY'::character varying, 'SAFE_PURSUIT'::character varying, 'PROFIT_PURSUIT'::character varying, 'AGGRESSIVE'::character varying, 'ULTRA_SHORT'::character varying, 'SHORT'::character varying, 'MID'::character varying, 'LONG'::character varying])::text[]))),
    CONSTRAINT hojumoney_recommendations_risk_profile_check CHECK (((risk_profile)::text = ANY ((ARRAY['CAPITAL_PROTECTION'::character varying, 'DIVIDEND_INCOME'::character varying, 'STEADY_GROWTH'::character varying, 'CAPITAL_GAIN'::character varying, 'STABILITY'::character varying, 'SAFE_PURSUIT'::character varying, 'PROFIT_PURSUIT'::character varying, 'AGGRESSIVE'::character varying, 'ULTRA_SHORT'::character varying, 'SHORT'::character varying, 'MID'::character varying, 'LONG'::character varying])::text[])))
);


--
-- Name: hojumoney_recommendations_hojumoney_recommendation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.hojumoney_recommendations ALTER COLUMN hojumoney_recommendation_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hojumoney_recommendations_hojumoney_recommendation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hts_stocks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.hts_stocks (
    base_date date NOT NULL,
    hts_stock_id bigint NOT NULL,
    stock_id bigint NOT NULL,
    search_type character varying(30) NOT NULL,
    CONSTRAINT hts_stocks_search_type_check CHECK (((search_type)::text = ANY ((ARRAY['STABILITY'::character varying, 'SAFE_PURSUIT'::character varying, 'PROFIT_PURSUIT'::character varying, 'AGGRESSIVE'::character varying])::text[])))
);


--
-- Name: hts_stocks_hts_stock_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.hts_stocks ALTER COLUMN hts_stock_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hts_stocks_hts_stock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: master_cases; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.master_cases (
    master_case_id bigint NOT NULL,
    master_id bigint NOT NULL,
    investment_period character varying(50) NOT NULL,
    sector character varying(50) NOT NULL,
    stock_name character varying(50) NOT NULL,
    investment_result character varying(100) NOT NULL,
    title character varying(100) NOT NULL,
    description text NOT NULL
);


--
-- Name: master_cases_master_case_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.master_cases ALTER COLUMN master_case_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.master_cases_master_case_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: master_options; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.master_options (
    display_order integer NOT NULL,
    master_id bigint NOT NULL,
    master_option_id bigint NOT NULL,
    logic_code character varying(50) NOT NULL,
    content character varying(100) NOT NULL,
    description text NOT NULL,
    CONSTRAINT master_options_logic_code_check CHECK (((logic_code)::text = ANY ((ARRAY['BUFFETT_ROE'::character varying, 'BUFFETT_PER'::character varying, 'BUFFETT_EPS_GROWTH'::character varying, 'BUFFETT_DEBT_RATIO'::character varying, 'BUFFETT_OPERATING_MARGIN'::character varying, 'LYNCH_PEG'::character varying, 'LYNCH_EPS_GROWTH'::character varying, 'LYNCH_DEBT_RATIO'::character varying, 'LYNCH_SALES_GROWTH'::character varying, 'LYNCH_SECTOR'::character varying, 'DALIO_ALL_WEATHER'::character varying, 'DALIO_PER'::character varying, 'DALIO_MARGIN_DEBT'::character varying, 'DALIO_DEBT_RATIO'::character varying, 'DALIO_EARNINGS_YIELD'::character varying, 'ONEIL_EPS_GROWTH'::character varying, 'ONEIL_ROE'::character varying, 'ONEIL_HIGH_52_WEEK'::character varying, 'ONEIL_MARKET_LEADER'::character varying, 'ONEIL_INST_NET_BUY'::character varying])::text[])))
);


--
-- Name: master_options_master_option_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.master_options ALTER COLUMN master_option_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.master_options_master_option_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: master_portfolio_stocks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.master_portfolio_stocks (
    weight numeric(10,4) NOT NULL,
    master_id bigint NOT NULL,
    master_portfolio_stock_id bigint NOT NULL,
    sector character varying(50) NOT NULL,
    stock_name character varying(50) NOT NULL
);


--
-- Name: master_portfolio_stocks_master_portfolio_stock_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.master_portfolio_stocks ALTER COLUMN master_portfolio_stock_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.master_portfolio_stocks_master_portfolio_stock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: master_principles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.master_principles (
    master_id bigint NOT NULL,
    master_principle_id bigint NOT NULL,
    title character varying(100) NOT NULL,
    description text NOT NULL,
    details jsonb
);


--
-- Name: master_principles_master_principle_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.master_principles ALTER COLUMN master_principle_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.master_principles_master_principle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: master_recommendations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.master_recommendations (
    master_id bigint NOT NULL,
    master_recommendation_id bigint NOT NULL,
    recommendation_id bigint NOT NULL,
    selected_option_ids jsonb NOT NULL
);


--
-- Name: master_recommendations_master_recommendation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.master_recommendations ALTER COLUMN master_recommendation_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.master_recommendations_master_recommendation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: master_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.master_tags (
    master_id bigint NOT NULL,
    master_tag_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


--
-- Name: master_tags_master_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.master_tags ALTER COLUMN master_tag_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.master_tags_master_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: masters; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.masters (
    display_order integer NOT NULL,
    master_id bigint NOT NULL,
    master_code character varying(30) NOT NULL,
    master_name character varying(50) NOT NULL,
    portfolio_base_period character varying(50) NOT NULL,
    philosophy_title character varying(100) NOT NULL,
    image_file_name character varying(200),
    quote character varying(200),
    philosophy_description text NOT NULL,
    recommendation_description text NOT NULL,
    CONSTRAINT masters_master_code_check CHECK (((master_code)::text = ANY ((ARRAY['WARREN_BUFFETT'::character varying, 'PETER_LYNCH'::character varying, 'RAY_DALIO'::character varying, 'WILLIAM_ONEIL'::character varying])::text[])))
);


--
-- Name: masters_master_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.masters ALTER COLUMN master_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.masters_master_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recommendation_stock_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recommendation_stock_tags (
    recommendation_stock_id bigint,
    recommendation_stock_tag_id bigint NOT NULL,
    tag_type character varying(30) NOT NULL,
    tag_name character varying(100) NOT NULL,
    CONSTRAINT recommendation_stock_tags_tag_type_check CHECK (((tag_type)::text = ANY ((ARRAY['SURVEY_LOGIC'::character varying, 'MASTER_OPTION'::character varying, 'GOOD_SECTOR'::character varying])::text[])))
);


--
-- Name: recommendation_stock_tags_recommendation_stock_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recommendation_stock_tags ALTER COLUMN recommendation_stock_tag_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recommendation_stock_tags_recommendation_stock_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recommendation_stocks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recommendation_stocks (
    change_rate numeric(10,4),
    current_price numeric(20,4),
    matched_condition_count integer NOT NULL,
    recommendation_rank integer NOT NULL,
    sort_metric_value numeric(20,4),
    recommendation_id bigint NOT NULL,
    recommendation_stock_id bigint NOT NULL,
    stock_id bigint NOT NULL,
    sort_metric_key character varying(50) NOT NULL
);


--
-- Name: recommendation_stocks_recommendation_stock_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recommendation_stocks ALTER COLUMN recommendation_stock_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recommendation_stocks_recommendation_stock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recommendations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recommendations (
    created_at timestamp(6) without time zone NOT NULL,
    recommendation_id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    recommendation_type character varying(30) NOT NULL,
    CONSTRAINT recommendations_recommendation_type_check CHECK (((recommendation_type)::text = ANY ((ARRAY['HOJUMONEY'::character varying, 'MASTER'::character varying])::text[])))
);


--
-- Name: recommendations_recommendation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recommendations ALTER COLUMN recommendation_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recommendations_recommendation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sectors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sectors (
    sector_id bigint NOT NULL,
    sector_name character varying(50) NOT NULL,
    CONSTRAINT sectors_sector_name_check CHECK (((sector_name)::text = ANY ((ARRAY['IT_SEMICONDUCTOR'::character varying, 'AUTOMOBILE_TRANSPORT'::character varying, 'ENERGY_CHEMISTRY'::character varying, 'BIO_HEALTHCARE'::character varying, 'SHIPBUILDING_MACHINERY'::character varying, 'FINANCE'::character varying, 'COMMUNICATION'::character varying, 'STEEL_MATERIALS'::character varying, 'CONSTRUCTION_UTILITY'::character varying, 'ESSENTIAL_CONSUMER'::character varying])::text[])))
);


--
-- Name: sectors_sector_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sectors ALTER COLUMN sector_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sectors_sector_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_indicators; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock_indicators (
    current_eps numeric(19,4) NOT NULL,
    debt_ratio numeric(19,4) NOT NULL,
    dividend_yield numeric(19,4) NOT NULL,
    dps numeric(19,4) NOT NULL,
    execution_strength numeric(19,4),
    high52_week_rate numeric(19,4) NOT NULL,
    last_year_eps numeric(19,4),
    margin_debt_rate numeric(19,4) NOT NULL,
    operating_profit_growth_rate numeric(19,4) NOT NULL,
    payout_ratio numeric(19,4),
    pbr numeric(19,4) NOT NULL,
    per numeric(19,4) NOT NULL,
    roe numeric(19,4) NOT NULL,
    base_time character varying(6) NOT NULL,
    accumulated_trade_amount bigint NOT NULL,
    current_sales bigint NOT NULL,
    indicator_id bigint NOT NULL,
    inst_net_buy20_days bigint NOT NULL,
    last_year_sales bigint,
    market_cap bigint NOT NULL,
    operating_profit bigint NOT NULL,
    stock_id bigint NOT NULL
);


--
-- Name: stock_indicators_indicator_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stock_indicators ALTER COLUMN indicator_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_indicators_indicator_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_term_learnings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock_term_learnings (
    created_at timestamp(6) without time zone NOT NULL,
    learning_id bigint NOT NULL,
    term_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: stock_term_learnings_learning_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stock_term_learnings ALTER COLUMN learning_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_term_learnings_learning_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_term_scraps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock_term_scraps (
    created_at timestamp(6) without time zone NOT NULL,
    scrap_id bigint NOT NULL,
    term_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: stock_term_scraps_scrap_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stock_term_scraps ALTER COLUMN scrap_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_term_scraps_scrap_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_terms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock_terms (
    term_id bigint NOT NULL,
    category character varying(30) NOT NULL,
    term_name character varying(50) NOT NULL,
    image_file_name character varying(100) NOT NULL,
    subtitle character varying(100) NOT NULL,
    description text NOT NULL,
    CONSTRAINT stock_terms_category_check CHECK (((category)::text = ANY ((ARRAY['BASIC_CONCEPT'::character varying, 'COMPANY_DIAGNOSIS'::character varying, 'CHART_ANALYSIS'::character varying, 'TRADING_PRACTICE'::character varying])::text[])))
);


--
-- Name: stock_terms_term_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stock_terms ALTER COLUMN term_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_terms_term_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stocks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stocks (
    is_market_leader boolean NOT NULL,
    sector_id bigint NOT NULL,
    stock_id bigint NOT NULL,
    stock_code character varying(10) NOT NULL,
    market_type character varying(20) NOT NULL,
    name character varying(50) NOT NULL,
    description jsonb,
    CONSTRAINT stocks_market_type_check CHECK (((market_type)::text = ANY ((ARRAY['KOSPI'::character varying, 'KOSDAQ'::character varying])::text[])))
);


--
-- Name: stocks_stock_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stocks ALTER COLUMN stock_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stocks_stock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: survey_option_restrictions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.survey_option_restrictions (
    restricted_option_id bigint NOT NULL,
    restriction_id bigint NOT NULL,
    source_option_id bigint NOT NULL
);


--
-- Name: survey_option_restrictions_restriction_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.survey_option_restrictions ALTER COLUMN restriction_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.survey_option_restrictions_restriction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: survey_options; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.survey_options (
    display_order integer NOT NULL,
    survey_option_id bigint NOT NULL,
    survey_question_id bigint NOT NULL,
    logic_code character varying(40) NOT NULL,
    content character varying(255) NOT NULL,
    description jsonb NOT NULL,
    CONSTRAINT survey_options_logic_code_check CHECK (((logic_code)::text = ANY ((ARRAY['CAPITAL_PROTECTION'::character varying, 'DIVIDEND_INCOME'::character varying, 'STEADY_GROWTH'::character varying, 'CAPITAL_GAIN'::character varying, 'STABILITY'::character varying, 'SAFE_PURSUIT'::character varying, 'PROFIT_PURSUIT'::character varying, 'AGGRESSIVE'::character varying, 'ULTRA_SHORT'::character varying, 'SHORT'::character varying, 'MID'::character varying, 'LONG'::character varying])::text[])))
);


--
-- Name: survey_options_survey_option_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.survey_options ALTER COLUMN survey_option_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.survey_options_survey_option_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: survey_questions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.survey_questions (
    display_order integer NOT NULL,
    survey_question_id bigint NOT NULL,
    question_type character varying(30) NOT NULL,
    content character varying(255) NOT NULL,
    description text NOT NULL,
    CONSTRAINT survey_questions_question_type_check CHECK (((question_type)::text = ANY ((ARRAY['INVESTMENT_PURPOSE'::character varying, 'RISK_PROFILE'::character varying, 'INVESTMENT_HORIZON'::character varying])::text[])))
);


--
-- Name: survey_questions_survey_question_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.survey_questions ALTER COLUMN survey_question_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.survey_questions_survey_question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tags (
    tag_id bigint NOT NULL,
    tag_name character varying(50) NOT NULL
);


--
-- Name: tags_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tags ALTER COLUMN tag_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tags_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    selected_master_id bigint,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    provider character varying(20) NOT NULL,
    role character varying(20) NOT NULL,
    nickname character varying(100) NOT NULL,
    provider_id character varying(100) NOT NULL,
    service_nickname character varying(100),
    CONSTRAINT users_provider_check CHECK (((provider)::text = ANY ((ARRAY['KAKAO'::character varying, 'LOCAL'::character varying])::text[]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hojumoney_personas hojumoney_personas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hojumoney_personas
    ADD CONSTRAINT hojumoney_personas_pkey PRIMARY KEY (hojumoney_persona_id);


--
-- Name: hojumoney_recommendations hojumoney_recommendations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hojumoney_recommendations
    ADD CONSTRAINT hojumoney_recommendations_pkey PRIMARY KEY (hojumoney_recommendation_id);


--
-- Name: hojumoney_recommendations hojumoney_recommendations_recommendation_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hojumoney_recommendations
    ADD CONSTRAINT hojumoney_recommendations_recommendation_id_key UNIQUE (recommendation_id);


--
-- Name: hts_stocks hts_stocks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hts_stocks
    ADD CONSTRAINT hts_stocks_pkey PRIMARY KEY (hts_stock_id);


--
-- Name: masters idx_master_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.masters
    ADD CONSTRAINT idx_master_code UNIQUE (master_code);


--
-- Name: masters idx_master_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.masters
    ADD CONSTRAINT idx_master_name UNIQUE (master_name);


--
-- Name: master_options idx_master_option_logic_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.master_options
    ADD CONSTRAINT idx_master_option_logic_code UNIQUE (logic_code);


--
-- Name: master_tags idx_master_tag_master_tag; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.master_tags
    ADD CONSTRAINT idx_master_tag_master_tag UNIQUE (master_id, tag_id);


--
-- Name: stocks idx_stock_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stocks
    ADD CONSTRAINT idx_stock_code UNIQUE (stock_code);


--
-- Name: survey_options idx_survey_option_logic_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.survey_options
    ADD CONSTRAINT idx_survey_option_logic_code UNIQUE (logic_code);


--
-- Name: survey_questions idx_survey_question_type; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.survey_questions
    ADD CONSTRAINT idx_survey_question_type UNIQUE (question_type);


--
-- Name: tags idx_tag_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT idx_tag_name UNIQUE (tag_name);


--
-- Name: master_cases master_cases_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.master_cases
    ADD CONSTRAINT master_cases_pkey PRIMARY KEY (master_case_id);


--
-- Name: master_options master_options_logic_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.master_options
    ADD CONSTRAINT master_options_logic_code_key UNIQUE (logic_code);


--
-- Name: master_options master_options_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.master_options
    ADD CONSTRAINT master_options_pkey PRIMARY KEY (master_option_id);


--
-- Name: master_portfolio_stocks master_portfolio_stocks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.master_portfolio_stocks
    ADD CONSTRAINT master_portfolio_stocks_pkey PRIMARY KEY (master_portfolio_stock_id);


--
-- Name: master_principles master_principles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.master_principles
    ADD CONSTRAINT master_principles_pkey PRIMARY KEY (master_principle_id);


--
-- Name: master_recommendations master_recommendations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.master_recommendations
    ADD CONSTRAINT master_recommendations_pkey PRIMARY KEY (master_recommendation_id);


--
-- Name: master_recommendations master_recommendations_recommendation_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.master_recommendations
    ADD CONSTRAINT master_recommendations_recommendation_id_key UNIQUE (recommendation_id);


--
-- Name: master_tags master_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.master_tags
    ADD CONSTRAINT master_tags_pkey PRIMARY KEY (master_tag_id);


--
-- Name: masters masters_master_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.masters
    ADD CONSTRAINT masters_master_code_key UNIQUE (master_code);


--
-- Name: masters masters_master_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.masters
    ADD CONSTRAINT masters_master_name_key UNIQUE (master_name);


--
-- Name: masters masters_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.masters
    ADD CONSTRAINT masters_pkey PRIMARY KEY (master_id);


--
-- Name: recommendation_stock_tags recommendation_stock_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendation_stock_tags
    ADD CONSTRAINT recommendation_stock_tags_pkey PRIMARY KEY (recommendation_stock_tag_id);


--
-- Name: recommendation_stocks recommendation_stocks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendation_stocks
    ADD CONSTRAINT recommendation_stocks_pkey PRIMARY KEY (recommendation_stock_id);


--
-- Name: recommendations recommendations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendations
    ADD CONSTRAINT recommendations_pkey PRIMARY KEY (recommendation_id);


--
-- Name: sectors sectors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sectors
    ADD CONSTRAINT sectors_pkey PRIMARY KEY (sector_id);


--
-- Name: sectors sectors_sector_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sectors
    ADD CONSTRAINT sectors_sector_name_key UNIQUE (sector_name);


--
-- Name: stock_indicators stock_indicators_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_indicators
    ADD CONSTRAINT stock_indicators_pkey PRIMARY KEY (indicator_id);


--
-- Name: stock_term_learnings stock_term_learnings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_term_learnings
    ADD CONSTRAINT stock_term_learnings_pkey PRIMARY KEY (learning_id);


--
-- Name: stock_term_scraps stock_term_scraps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_term_scraps
    ADD CONSTRAINT stock_term_scraps_pkey PRIMARY KEY (scrap_id);


--
-- Name: stock_terms stock_terms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_terms
    ADD CONSTRAINT stock_terms_pkey PRIMARY KEY (term_id);


--
-- Name: stocks stocks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stocks
    ADD CONSTRAINT stocks_pkey PRIMARY KEY (stock_id);


--
-- Name: survey_option_restrictions survey_option_restrictions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.survey_option_restrictions
    ADD CONSTRAINT survey_option_restrictions_pkey PRIMARY KEY (restriction_id);


--
-- Name: survey_options survey_options_logic_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.survey_options
    ADD CONSTRAINT survey_options_logic_code_key UNIQUE (logic_code);


--
-- Name: survey_options survey_options_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.survey_options
    ADD CONSTRAINT survey_options_pkey PRIMARY KEY (survey_option_id);


--
-- Name: survey_questions survey_questions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.survey_questions
    ADD CONSTRAINT survey_questions_pkey PRIMARY KEY (survey_question_id);


--
-- Name: survey_questions survey_questions_question_type_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.survey_questions
    ADD CONSTRAINT survey_questions_question_type_key UNIQUE (question_type);


--
-- Name: tags tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_pkey PRIMARY KEY (tag_id);


--
-- Name: tags tags_tag_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_tag_name_key UNIQUE (tag_name);


--
-- Name: hojumoney_personas uk_hojumoney_persona_combination; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hojumoney_personas
    ADD CONSTRAINT uk_hojumoney_persona_combination UNIQUE (investment_purpose, risk_profile, investment_horizon);


--
-- Name: hts_stocks uk_hts_stock_stock_search_type_base_date; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hts_stocks
    ADD CONSTRAINT uk_hts_stock_stock_search_type_base_date UNIQUE (stock_id, search_type, base_date);


--
-- Name: users uk_provider_providerid; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_provider_providerid UNIQUE (provider, provider_id);


--
-- Name: recommendation_stocks uk_recommendation_stock_recommendation_rank; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendation_stocks
    ADD CONSTRAINT uk_recommendation_stock_recommendation_rank UNIQUE (recommendation_id, recommendation_rank);


--
-- Name: recommendation_stock_tags uk_recommendation_stock_tag; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendation_stock_tags
    ADD CONSTRAINT uk_recommendation_stock_tag UNIQUE (recommendation_stock_id, tag_type, tag_name);


--
-- Name: stock_indicators uk_stock_indicator_stock_base_time; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_indicators
    ADD CONSTRAINT uk_stock_indicator_stock_base_time UNIQUE (stock_id, base_time);


--
-- Name: stock_term_learnings uk_stock_term_learning_user_term; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_term_learnings
    ADD CONSTRAINT uk_stock_term_learning_user_term UNIQUE (user_id, term_id);


--
-- Name: stock_term_scraps uk_stock_term_scrap_user_term; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_term_scraps
    ADD CONSTRAINT uk_stock_term_scrap_user_term UNIQUE (user_id, term_id);


--
-- Name: survey_option_restrictions uk_survey_option_restriction_source_restricted; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.survey_option_restrictions
    ADD CONSTRAINT uk_survey_option_restriction_source_restricted UNIQUE (source_option_id, restricted_option_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: idx_hojumoney_persona_combination; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_hojumoney_persona_combination ON public.hojumoney_personas USING btree (investment_purpose, risk_profile, investment_horizon);


--
-- Name: idx_hts_stock_search_type_base_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_hts_stock_search_type_base_date ON public.hts_stocks USING btree (search_type, base_date);


--
-- Name: idx_hts_stock_stock_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_hts_stock_stock_id ON public.hts_stocks USING btree (stock_id);


--
-- Name: idx_master_case_master_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_master_case_master_id ON public.master_cases USING btree (master_id);


--
-- Name: idx_master_option_master_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_master_option_master_id ON public.master_options USING btree (master_id);


--
-- Name: idx_master_portfolio_stock_master_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_master_portfolio_stock_master_id ON public.master_portfolio_stocks USING btree (master_id);


--
-- Name: idx_master_principle_master_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_master_principle_master_id ON public.master_principles USING btree (master_id);


--
-- Name: idx_master_tag_master_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_master_tag_master_id ON public.master_tags USING btree (master_id);


--
-- Name: idx_master_tag_tag_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_master_tag_tag_id ON public.master_tags USING btree (tag_id);


--
-- Name: idx_recommendation_stock_recommendation; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_recommendation_stock_recommendation ON public.recommendation_stocks USING btree (recommendation_id);


--
-- Name: idx_recommendation_stock_tag_stock; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_recommendation_stock_tag_stock ON public.recommendation_stock_tags USING btree (recommendation_stock_id);


--
-- Name: idx_recommendation_user_type_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_recommendation_user_type_created_at ON public.recommendations USING btree (user_id, recommendation_type, created_at);


--
-- Name: idx_stock_indicator_base_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stock_indicator_base_time ON public.stock_indicators USING btree (base_time);


--
-- Name: idx_stock_indicator_stock_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stock_indicator_stock_id ON public.stock_indicators USING btree (stock_id);


--
-- Name: idx_stock_term_category; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stock_term_category ON public.stock_terms USING btree (category);


--
-- Name: idx_stock_term_learning_term_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stock_term_learning_term_id ON public.stock_term_learnings USING btree (term_id);


--
-- Name: idx_stock_term_learning_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stock_term_learning_user_id ON public.stock_term_learnings USING btree (user_id);


--
-- Name: idx_stock_term_scrap_term_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stock_term_scrap_term_id ON public.stock_term_scraps USING btree (term_id);


--
-- Name: idx_stock_term_scrap_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stock_term_scrap_user_id ON public.stock_term_scraps USING btree (user_id);


--
-- Name: idx_stock_term_term_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stock_term_term_name ON public.stock_terms USING btree (term_name);


--
-- Name: idx_survey_option_question_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_survey_option_question_id ON public.survey_options USING btree (survey_question_id);


--
-- Name: idx_survey_option_restriction_restricted; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_survey_option_restriction_restricted ON public.survey_option_restrictions USING btree (restricted_option_id);


--
-- Name: idx_survey_option_restriction_source; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_survey_option_restriction_source ON public.survey_option_restrictions USING btree (source_option_id);


--
-- Name: idx_survey_question_display_order; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_survey_question_display_order ON public.survey_questions USING btree (display_order);


--
-- Name: idx_user_provider_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_provider_id ON public.users USING btree (provider_id);


--
-- Name: master_recommendations fk21p5vawjhtvkn2500d57n44yq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.master_recommendations
    ADD CONSTRAINT fk21p5vawjhtvkn2500d57n44yq FOREIGN KEY (master_id) REFERENCES public.masters(master_id);


--
-- Name: survey_option_restrictions fk2iiawi50vxv85vv1asmgh89tx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.survey_option_restrictions
    ADD CONSTRAINT fk2iiawi50vxv85vv1asmgh89tx FOREIGN KEY (source_option_id) REFERENCES public.survey_options(survey_option_id);


--
-- Name: recommendations fk3c9w1lipqdutm65a9inevwfp0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendations
    ADD CONSTRAINT fk3c9w1lipqdutm65a9inevwfp0 FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: stock_indicators fk61yh4x2svp87ff1a2jias72sj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_indicators
    ADD CONSTRAINT fk61yh4x2svp87ff1a2jias72sj FOREIGN KEY (stock_id) REFERENCES public.stocks(stock_id);


--
-- Name: hojumoney_recommendations fk7rp4o86chg68bbtvrw17m8o8y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hojumoney_recommendations
    ADD CONSTRAINT fk7rp4o86chg68bbtvrw17m8o8y FOREIGN KEY (recommendation_id) REFERENCES public.recommendations(recommendation_id);


--
-- Name: users fk89k9mso96042b3ghpda1guo86; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk89k9mso96042b3ghpda1guo86 FOREIGN KEY (selected_master_id) REFERENCES public.masters(master_id);


--
-- Name: master_portfolio_stocks fk8os6nrldd3sgm8cbq9m5hejyh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.master_portfolio_stocks
    ADD CONSTRAINT fk8os6nrldd3sgm8cbq9m5hejyh FOREIGN KEY (master_id) REFERENCES public.masters(master_id);


--
-- Name: stocks fk8wd5x71oqmico6tm0vslrjutu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stocks
    ADD CONSTRAINT fk8wd5x71oqmico6tm0vslrjutu FOREIGN KEY (sector_id) REFERENCES public.sectors(sector_id);


--
-- Name: recommendation_stocks fkadub1p3h3a04gxui7yt6rc3qh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendation_stocks
    ADD CONSTRAINT fkadub1p3h3a04gxui7yt6rc3qh FOREIGN KEY (recommendation_id) REFERENCES public.recommendations(recommendation_id);


--
-- Name: hts_stocks fkaoev15c53i6coppp8nsws94yk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hts_stocks
    ADD CONSTRAINT fkaoev15c53i6coppp8nsws94yk FOREIGN KEY (stock_id) REFERENCES public.stocks(stock_id);


--
-- Name: master_tags fkb15o7yuialwu79m9j21a2tl0p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.master_tags
    ADD CONSTRAINT fkb15o7yuialwu79m9j21a2tl0p FOREIGN KEY (master_id) REFERENCES public.masters(master_id);


--
-- Name: master_options fkhmbyaotcumy15w76yidx7raip; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.master_options
    ADD CONSTRAINT fkhmbyaotcumy15w76yidx7raip FOREIGN KEY (master_id) REFERENCES public.masters(master_id);


--
-- Name: master_cases fklkg9g4tw67tb53auabve2nx8y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.master_cases
    ADD CONSTRAINT fklkg9g4tw67tb53auabve2nx8y FOREIGN KEY (master_id) REFERENCES public.masters(master_id);


--
-- Name: stock_term_scraps fklwf3acaqrqeahtpl23ekh4rax; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_term_scraps
    ADD CONSTRAINT fklwf3acaqrqeahtpl23ekh4rax FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: recommendation_stocks fkmd0mnyk95k09fvrckmy9v3jeq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendation_stocks
    ADD CONSTRAINT fkmd0mnyk95k09fvrckmy9v3jeq FOREIGN KEY (stock_id) REFERENCES public.stocks(stock_id);


--
-- Name: master_principles fkmuuxq0ftageq1gmnq668hm0dn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.master_principles
    ADD CONSTRAINT fkmuuxq0ftageq1gmnq668hm0dn FOREIGN KEY (master_id) REFERENCES public.masters(master_id);


--
-- Name: stock_term_scraps fkn17n51a5m1ixge7c0yy98ruqr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_term_scraps
    ADD CONSTRAINT fkn17n51a5m1ixge7c0yy98ruqr FOREIGN KEY (term_id) REFERENCES public.stock_terms(term_id);


--
-- Name: survey_options fkn87ahvka3clypnvvshnj7fv8r; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.survey_options
    ADD CONSTRAINT fkn87ahvka3clypnvvshnj7fv8r FOREIGN KEY (survey_question_id) REFERENCES public.survey_questions(survey_question_id);


--
-- Name: master_tags fknjev8l0odapcltskcb29xoi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.master_tags
    ADD CONSTRAINT fknjev8l0odapcltskcb29xoi FOREIGN KEY (tag_id) REFERENCES public.tags(tag_id);


--
-- Name: recommendation_stock_tags fkp8rrqtvn5pdqi8lw6sdivdn0v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendation_stock_tags
    ADD CONSTRAINT fkp8rrqtvn5pdqi8lw6sdivdn0v FOREIGN KEY (recommendation_stock_id) REFERENCES public.recommendation_stocks(recommendation_stock_id);


--
-- Name: master_recommendations fkqq1y76d3b0yg4lr180hkwn3d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.master_recommendations
    ADD CONSTRAINT fkqq1y76d3b0yg4lr180hkwn3d FOREIGN KEY (recommendation_id) REFERENCES public.recommendations(recommendation_id);


--
-- Name: stock_term_learnings fksl2i2vp4qg3dtdhag3e6leony; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_term_learnings
    ADD CONSTRAINT fksl2i2vp4qg3dtdhag3e6leony FOREIGN KEY (term_id) REFERENCES public.stock_terms(term_id);


--
-- Name: survey_option_restrictions fktb4kyr4toajrl723ysv4m7132; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.survey_option_restrictions
    ADD CONSTRAINT fktb4kyr4toajrl723ysv4m7132 FOREIGN KEY (restricted_option_id) REFERENCES public.survey_options(survey_option_id);


--
-- Name: stock_term_learnings fktdx31tae4l37jhib1qi5uen45; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_term_learnings
    ADD CONSTRAINT fktdx31tae4l37jhib1qi5uen45 FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- PostgreSQL database dump complete
--


