CREATE TABLE accounts (
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    seed_money NUMERIC(20, 4) NOT NULL,
    cash_balance NUMERIC(20, 4) NOT NULL,
    total_purchase_amount NUMERIC(20, 4) NOT NULL,
    total_asset NUMERIC(20, 4) NOT NULL,
    total_profit_rate NUMERIC(10, 4),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_account_user UNIQUE (user_id),
    CONSTRAINT fk_account_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE INDEX idx_account_user_id ON accounts(user_id);

CREATE TABLE portfolios (
    portfolio_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    stock_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    average_purchase_price NUMERIC(20, 4) NOT NULL,
    total_purchase_amount NUMERIC(20, 4) NOT NULL,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_portfolio_account_stock UNIQUE (account_id, stock_id),
    CONSTRAINT fk_portfolio_account FOREIGN KEY (account_id) REFERENCES accounts(account_id) ON DELETE CASCADE,
    CONSTRAINT fk_portfolio_stock FOREIGN KEY (stock_id) REFERENCES stocks(stock_id),
    CONSTRAINT chk_portfolio_quantity_positive CHECK (quantity > 0)
);

CREATE INDEX idx_portfolio_account_id ON portfolios(account_id);
CREATE INDEX idx_portfolio_stock_id ON portfolios(stock_id);

CREATE TABLE orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    stock_id BIGINT,
    order_type VARCHAR(20) NOT NULL,
    execution_price NUMERIC(20, 4) NOT NULL,
    quantity INTEGER NOT NULL,
    total_execution_amount NUMERIC(20, 4) NOT NULL,
    executed_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_order_account FOREIGN KEY (account_id) REFERENCES accounts(account_id) ON DELETE CASCADE,
    CONSTRAINT fk_order_stock FOREIGN KEY (stock_id) REFERENCES stocks(stock_id),
    CONSTRAINT chk_order_type CHECK (order_type IN ('DEPOSIT', 'BUY', 'SELL')),
    CONSTRAINT chk_order_quantity_positive CHECK (quantity > 0)
);

CREATE INDEX idx_order_account_executed_at ON orders(account_id, executed_at);
CREATE INDEX idx_order_stock_id ON orders(stock_id);
