CREATE TABLE stock_candles (
    stock_candle_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id BIGINT NOT NULL,
    stock_code VARCHAR(10) NOT NULL,
    interval_type VARCHAR(20) NOT NULL,
    candle_time TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    open_price NUMERIC(20, 4) NOT NULL,
    high_price NUMERIC(20, 4) NOT NULL,
    low_price NUMERIC(20, 4) NOT NULL,
    close_price NUMERIC(20, 4) NOT NULL,
    volume BIGINT NOT NULL,
    trade_amount BIGINT,
    is_final BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_stock_candle_stock_interval_time UNIQUE (stock_id, interval_type, candle_time),
    CONSTRAINT fk_stock_candle_stock FOREIGN KEY (stock_id) REFERENCES stocks(stock_id),
    CONSTRAINT chk_stock_candle_interval_type CHECK (interval_type IN ('MINUTE', 'DAY', 'WEEK', 'MONTH', 'YEAR'))
);

CREATE INDEX idx_stock_candle_stock_interval_time ON stock_candles(stock_id, interval_type, candle_time);
CREATE INDEX idx_stock_candle_code_interval_time ON stock_candles(stock_code, interval_type, candle_time);
