CREATE TABLE verified_operation_trade_lots (
    verified_operation_trade_lot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_code VARCHAR(100) NOT NULL,
    account_id BIGINT NOT NULL,
    stock_id BIGINT NOT NULL,
    buy_order_id BIGINT NOT NULL,
    sell_order_id BIGINT,
    quantity INTEGER NOT NULL,
    remaining_quantity INTEGER NOT NULL,
    bought_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    sell_due_at TIMESTAMP(6) WITHOUT TIME ZONE,
    closed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT fk_verified_operation_lot_account FOREIGN KEY (account_id) REFERENCES accounts(account_id) ON DELETE CASCADE,
    CONSTRAINT fk_verified_operation_lot_stock FOREIGN KEY (stock_id) REFERENCES stocks(stock_id),
    CONSTRAINT fk_verified_operation_lot_buy_order FOREIGN KEY (buy_order_id) REFERENCES orders(order_id),
    CONSTRAINT fk_verified_operation_lot_sell_order FOREIGN KEY (sell_order_id) REFERENCES orders(order_id),
    CONSTRAINT chk_verified_operation_lot_quantity_positive CHECK (quantity > 0),
    CONSTRAINT chk_verified_operation_lot_remaining_non_negative CHECK (remaining_quantity >= 0)
);

CREATE INDEX idx_verified_operation_lot_account_code_due
    ON verified_operation_trade_lots(account_code, sell_due_at, remaining_quantity);

CREATE INDEX idx_verified_operation_lot_account_id
    ON verified_operation_trade_lots(account_id);

CREATE INDEX idx_verified_operation_lot_buy_order_id
    ON verified_operation_trade_lots(buy_order_id);
