CREATE TABLE today_stock_terms (
    today_stock_term_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_term_id BIGINT NOT NULL,
    target_date DATE NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_today_stock_terms_target_date UNIQUE (target_date),
    CONSTRAINT fk_today_stock_terms_stock_term FOREIGN KEY (stock_term_id) REFERENCES stock_terms(term_id)
);

CREATE INDEX idx_today_stock_terms_stock_term_id
    ON today_stock_terms(stock_term_id);
